### ISSUE TITLE
AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [ddmitov/perl-executing-browser#10]
https://github.com/ddmitov/perl-executing-browser/blob/c28a47e7bdb6b5742d4aacb697fb1aeb0836dc32/appimage-maker.sh#L3

Please make the resulting AppImage available for download on GitHub Releases. Thanks. This way we can put it into the AppImageHub central directory of available AppImages.

**Comment by ddmitov** [comment]
Dear probono,

I enhanced the AppImage support of PEB in a series of commits and now we have PEB version 0.7 with an AppImage included in the release. I will be very glad and thankful if you include PEB in the AppImageHub and please give me a link when you do this. I have no AppStream metainfo file now, but I can correct this soon.

With all my best wishes,
Dimitar Mitov

**Comment by probonopd** [comment]
Dear @ddmitov, thanks for making an AppImage. I will happily include it in AppImageHub. RIght now there is an issue that needs to be fixed:

The desktop file is lacking a `Categories=` entry in the `*.desktop` file.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, please add at least one of the following in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

__electron-builder offers native support for this since [v19.22.1](https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1).__. Please see the `category` key at https://www.electron.build/configuration/linux-other.

Reference: https://github.com/AppImage/AppImageHub/issues/2

**Comment by ddmitov** [comment]
Dear probono,

I will check the peb.desktop file ASAP an I will make sure that it conforms to the standard.
Then I can make a minor release to share the resulting AppImage.

With all my best wishes,
Dimitar Mitov

**Comment by ddmitov** [comment]
Dear probono,

A new minor release of PEB is already a fact. I created metainfo file and updated peb.desktop, which passed desktop-file-validate checks. Links to screenshots are also included in the metainfo file. I hope that now the latest PEB AppImage is up to the AppImage standards. If something else has to be fixed, please write again. I will not close the issue until all AppImage problems of PEB are fixed.

With all my best wishes,
Dimitar Mitov

**Comment by probonopd** [comment]
Dear @ddmitov thanks for your commitment. Currently it looks like the AppImage was built on a "too new" system which will make it fail to run on the oldest still-supported LTS release of Ubuntu, which is 14.04 at the moment:

```
AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /run/firejail/appimage/.appimage-7056/lib/libQt5WebKit.so.5)
```

Can you please build on Ubuntu 14.04 or a similarly old system?

More information:
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems

Thank you.

**Comment by ddmitov** [comment]
Dear probono,

It will take me some time to build PEB on an Ubuntu 14.04 virtual machine, but I fully accept the idea of widest possible user base of all AppImages by building them on a not-so-recent OS. I will make another minor release when I am ready. Congratulations for the excellent documentation of the AppImage project!

With all my best wishes,
Dimitar Mitov

**Comment by probonopd** [comment]
Thank you very much, it's looking good now. Added to https://appimage.github.io/apps/

**Comment by ddmitov** [comment]
Thanks and appreciation from me too!
